// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfxsumlxhcewsexhwehx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmeHN1bWx4aGNld3NleGh3ZWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDgxMDYsImV4cCI6MjA3NDIyNDEwNn0.sUbOJrEdBbmPcldcer9mIMFV3buYcuK5KfVw2cg7nII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});